### ISSUE TITLE
Any chance this component be maintained? I'd love to see it running.

### ISSUE THREAD

**Issue by valinaga** [FolioReader/react-native-folio-reader#2]

**Comment by hebertialmeida** [comment]
We need contributors, because I am maintaining the iOS project, and I have never used react native.

**Comment by hebertialmeida** [comment]
Could you help us?

**Comment by valinaga** [comment]
:( Unfortunately I'm not so good at building react native components. I really would like this, but I'm not qualified.

**Comment by arthurlataks** [comment]
I have just recently created a bridge for this pod inside the application I'm working now on. I will take a look at this over the weekend probably.

**Comment by mnlbox** [comment]
@hebertialmeida Please add some note about maintainer request on README.md file of repo so maybe someone can continue this awesome project.

**Comment by amsdamsgram** [comment]
Hey @arthurlataks, do you know if you will have time to share your bridge?
Thanks!

**Comment by hebertialmeida** [comment]
Sorry, This project is not being maintained anymore. If you would like to maintain that let me know.
